### ISSUE TITLE
Add conda environment setup

### ISSUE THREAD

**Issue by jbisits** [janzika/MATH3261-5285#1]
We could add `dedalus_environment.yaml` [environment setup file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) so people could install the whole environment (with correct dedalus version) required to run the notebooks locally.

**Comment by jbisits** [comment]
I have been running things locally so can probably set this up.

**Comment by janzika** [comment]
Yes that would be excellent. Is it as simple as uploading yours? Would be good to then add a line or two explains how they use it if not on colab. 
Also, do you want to add that edit that enables video display you talked about in W1?

**Comment by jbisits** [comment]
>  Is it as simple as uploading yours? Would be good to then add a line or two explains how they use it if not on colab.

I think so and yes will do!

> Also, do you want to add that edit that enables video display you talked about in W1?

~This was related to the software UNSW has for giving online lectures/tutorials not the lab setup.~
Sorry only just realised what you mean here! I will look at this in a seperate PR as it did not work in every case and might be better to get this merged first.
